trigger:
  branches:
    include:
    - '*'
  tags:
    include:
    - 'v*'

jobs:
- job: build
  displayName: Build

  strategy:
    matrix:
      nompi:
        unused: ""
      greatlakes:
        unused: ""
      bridges:
        unused: ""
      comet:
        unused: ""
      stampede2:
        unused: ""

  pool:
    vmImage: 'ubuntu-18.04'

  steps:
  - checkout: self
  - script: echo "##vso[task.setvariable variable=tag;]$(git describe --all --abbrev=0 | sed 's/\//-/g')"
    displayName: Determine tag
  - script: ./build.sh -t $(tag) -r glotzerlab $(System.JobName)
    displayName: Build image
  # - task: Docker@2
  #   displayName: Login to Docker Hub
  #   condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
  #   inputs:
  #     command: login
  #     containerRegistry: dockerHub
  - script: docker push glotzerlab/software
    displayName: Push image
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/v')
